version: '3.8'


services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - PGHOST=${HOST}
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=arina -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    platform: linux/amd64
    build: .
    volumes:
      - ./src:/opt/app
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=auth.test.org
      - VIRTUAL_PORT=8080
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT_5432_TCP_ADDR=${HOST}
      - POSTGRES_PORT_5432_TCP_PORT=${PORT}


volumes:
  postgres-db:
    driver: local
